"""Small dependency contracts shared by application services."""

from __future__ import annotations

from typing import Protocol


class LogSink(Protocol):
    def emit_text(self, message: str, tag: str | None = None) -> None: ...
    def emit_dim(self, message: str) -> None: ...
    def emit_error(self, message: str) -> None: ...
    def emit(self, rows: list) -> None: ...
    def flush(self) -> None: ...
