"""
html_assembler - build web/index.html from web/index.template.html.

The template uses simple `<!-- @include partials/foo.html -->` markers.
Each marker is replaced with the verbatim contents of the named partial
file (path is relative to web/). No conditionals, no variables, no nested
includes - just flat inclusion.

Called once at the start of `main.py` boot. The generated content is compared
with the existing `web/index.html`, and the file is rewritten only when the
bytes differ. This avoids stale output after git checkouts or copied files
where mtimes no longer prove freshness.

Why a build step at all?
    Patch 19 (v72.1) split the previously 1,953-line `web/index.html` into a
    small shell template plus per-tab and per-dialog partials, so contributors
    can read one section at a time. There's no Node or bundler in the project,
    so this Python helper takes the place of a build step.
"""
from __future__ import annotations

import re
from pathlib import Path

_INCLUDE_RE = re.compile(
    r"^(\s*)<!--\s*@include\s+(?P<path>[A-Za-z0-9_./-]+)\s*-->\s*$",
    re.MULTILINE,
)


def assemble_index_html(web_dir: Path | str) -> Path:
    """Assemble `index.template.html` plus partials into `index.html`.

    Returns the absolute path of the assembled file. Idempotent: if the
    generated bytes already match `index.html`, this is a no-op.
    """
    web = Path(web_dir)
    template = web / "index.template.html"
    output = web / "index.html"

    if not template.is_file():
        # No template means leave index.html alone. Some deployments may ship
        # a pre-assembled index.html without the template.
        return output

    src = template.read_text(encoding="utf-8")

    def _replace(match: re.Match[str]) -> str:
        indent = match.group(1) or ""
        rel = match.group("path")
        partial = web / rel
        try:
            body = partial.read_text(encoding="utf-8")
        except OSError as exc:
            return (
                f"{indent}<!-- @include failed: {rel}: {exc} -->\n"
                f"{indent}<!-- Re-running assembly may resolve this. -->"
            )

        # If the partial's lines are not already indented, add the marker's
        # indent to each non-blank line so the output reads cleanly.
        first_real = next((ln for ln in body.splitlines() if ln.strip()), "")
        if first_real and not first_real.startswith((" ", "\t")) and indent:
            body = "\n".join(
                (indent + ln) if ln.strip() else ln
                for ln in body.splitlines()
            )
        return body

    assembled = _INCLUDE_RE.sub(_replace, src)
    assembled = assembled.replace("\r\n", "\n").replace("\r", "\n")
    assembled_bytes = assembled.encode("utf-8")
    try:
        if output.read_bytes() == assembled_bytes:
            return output
    except OSError:
        pass

    output.write_bytes(assembled_bytes)
    return output


__all__ = ["assemble_index_html"]
